import type { Metadata } from "next"
import "./globals.css"
import { cn } from "@/app/_lib/utils"
import { Toaster } from "./components/ui/sonner"
import Footer from "./components/footer"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body className="antialiased">
        {children}
        <Toaster/>
        <Footer/>
      </body>
    </html>
  )
}
